### ISSUE TITLE
Component render sorunu

### ISSUE THREAD

**Issue by mertthesamael** [HATE-Company/Clone-Dictionary#1]
Selamlar, projeyi açtığımda componentler olması gerektiği gibi yüklenmiyor, ve projeyi yüklerken konsolda bazı error logları ile karşılaşıyorum. İlk olarak projenin açıldığı durumun ekran görüntüsünü ekliyorum :

![image](https://user-images.githubusercontent.com/79616834/200116635-99d145f4-f170-42d7-8ee3-97ab6b19bbb1.png)

Deneme olarak bi sidebar componenti eklediğimde sorunsuz yerleşyior

![image](https://user-images.githubusercontent.com/79616834/200116670-c7af0ade-440c-4aee-ab92-24dda4befd88.png)

Yarn ve NPM install durumundaki error logları şu şekilde ;
**NPM install log**
`npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 1548 packages, and audited 1549 packages in 3m

229 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.`

**Yarn install log**
`warning ..\..\..\..\..\package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning react-scripts > @svgr/webpack > @svgr/plugin-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning react-scripts > @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning react-scripts > css-minimizer-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @craco/craco@6.4.5" has incorrect peer dependency "react-scripts@^4.0.0".
warning "@craco/craco > cosmiconfig-typescript-loader@1.0.9" has unmet peer dependency "typescript@>=3".
warning "@craco/craco > cosmiconfig-typescript-loader > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "craco-less > less-loader@7.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 123.92s.`

**Denediğim çözümler**

- SVGO güncellemek (burda da bahsedilmiş bu sorundan ama bir işe yaramadı https://github.com/svg/svgo/issues/1689)
- İlk etapta hiçbir component yüklenmiyordu, bu sorunu yarn cachesini silip tekrar kurarak düzelttim
- Projeyi başka directorylerde açmayı denedim (Bikaç stackoverflow başlıklarında önerilen çözümlerdi)
- package-lock ve yarn.lock dosyalarını silip tekrar kurdum, tekrar bir sonuç alamadım

Şimdiden teşekkürler

**Comment by cemarguvanli** [comment]
oncelikle guzel issue acmissin eline saglik gayet aciklayici :) bu audit warningler'n hic bir onemi yok, react-router 6 kullaniyoruz belki icindeki bir kac dependency audit degildir ki bu bir sorun degil. yarn kullancim projede, yarn start dedigin de proje calisiyor bu guzel.

home'un icine bir div atip 1000px yukselik verirsen tum layout'u daha iyi gorursun. ya da lorem ipsun basabilirsib. benim ekranimdaki gibi aciliyor su an zaten bi sorun gormuyorum.

**Comment by mertthesamael** [comment]
> oncelikle guzel issue acmissin eline saglik gayet aciklayici :) bu audit warningler'n hic bir onemi yok, react-router 6 kullaniyoruz belki icindeki bir kac dependency audit degildir ki bu bir sorun degil. yarn kullancim projede, yarn start dedigin de proje calisiyor bu guzel.
> 
> home'un icine bir div atip 1000px yukselik verirsen tum layout'u daha iyi gorursun. ya da lorem ipsun basabilirsib. benim ekranimdaki gibi aciliyor su an zaten bi sorun gormuyorum.

Tamamdır, çok teşekkürler !
